#!/bin/bash

module load singularity 2> /dev/null

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

if [ ! -s dwi_fa.nii.gz ];
then
	echo "output missing"
	exit 1
fi
